# Generated by Django 3.0.1 on 2020-05-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200521_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='description',
        ),
    ]
