# Generated by Django 3.0.1 on 2020-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_remove_bug_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
